#pragma once

namespace orteaf::internal::kernel::registry {

// Generated by gen_kernel_registry.cpp in the build directory.
void registerAllGeneratedKernels();

} // namespace orteaf::internal::kernel::registry
