#pragma once

#if ORTEAF_ENABLE_MPS

#include <orteaf/internal/runtime/mps/platform/wrapper/mps_device.h>
#include <orteaf/internal/runtime/mps/platform/wrapper/mps_function.h>
#include <orteaf/internal/runtime/mps/platform/wrapper/mps_error.h>
#include <orteaf/internal/runtime/mps/platform/wrapper/mps_library.h>

#include <cstddef>
#include <span>
#include <string_view>

namespace orteaf::internal::runtime::mps::platform::metal_kernel_embed {

/**
 * @brief Access embedded Metal (MPS) metallib blobs generated by CMake.
 *
 * `.metal` sources placed under `orteaf/src/extension/kernel/mps/impl` are
 * compiled via `xcrun metal`/`metallib`, embedded into the binary, and exposed
 * through this registry.  These helpers allow backends to construct
 * `MTLLibrary` / `MTLFunction` objects without touching the filesystem, which
 * is convenient for tests and for distributing self-contained binaries.
 *
 * @par Usage example
 * @code{.mm}
 * using namespace orteaf::internal::runtime::mps::platform::wrapper;
 * using namespace orteaf::internal::runtime::mps::platform::metal_kernel_embed;
 *
 * MPSDevice_t device = acquire_default_device();  // user-defined helper
 * MPSError_t error = nullptr;
 * MPSLibrary_t lib = createEmbeddedLibrary(device, "embed_test_library", &error);
 * MPSFunction_t fn = createFunction(lib, "my_kernel");
 * // Continue with pipeline creation, command encoder setup, etc.
 * @endcode
 */

struct MetallibBlob {
    const void* data;
    std::size_t size;
};

struct MetallibEntry {
    const char* name;
    const unsigned char* begin;
    const unsigned char* end;
};

std::span<const MetallibEntry> libraries();

MetallibBlob findLibraryData(std::string_view library_name);

bool available(std::string_view library_name);

 ::orteaf::internal::runtime::mps::platform::wrapper::MPSLibrary_t createEmbeddedLibrary(
     ::orteaf::internal::runtime::mps::platform::wrapper::MPSDevice_t device,
     std::string_view library_name,
     ::orteaf::internal::runtime::mps::platform::wrapper::MPSError_t* error = nullptr);

} // namespace orteaf::internal::runtime::mps::platform::metal_kernel_embed

#endif  // ORTEAF_ENABLE_MPS
