#pragma once

#if ORTEAF_ENABLE_CUDA

#include <cstddef>
#include <string_view>

#ifndef ORTEAF_EMBED_HAS_FATBIN
#define ORTEAF_EMBED_HAS_FATBIN 0
#endif
#ifndef ORTEAF_EMBED_HAS_CUBIN
#define ORTEAF_EMBED_HAS_CUBIN 0
#endif
#ifndef ORTEAF_EMBED_HAS_PTX
#define ORTEAF_EMBED_HAS_PTX 0
#endif

namespace orteaf::internal::execution::cuda::platform::wrapper::kernel_embed {

/**
 * @brief Access embedded CUDA kernel blobs generated by CMake.
 *
 * Each `.cu` file under `orteaf/src/extension/kernel/cuda/impl` is compiled
 * during the build and packed into the final binary as a `fatbin`, `cubin`, or
 * `ptx` blob (see `ORTEAF_CUDA_KERNEL_FORMATS`).  The helpers in this namespace
 * provide a lightweight registry that lets you discover and feed those blobs
 * into the CUDA driver without re-reading files from disk.
 *
 * @par Usage example
 * @code{.cpp}
 * using namespace orteaf::internal::execution::cuda::platform::wrapper::kernel_embed;
 *
 * // Prefer a fatbin, but fall back to a PTX blob if fatbin generation was
 * // disabled for the current build.
 * Blob bin = findKernelData("embed_test_library",
 *                             CudaKernelFmt::Fatbin,
 *                             findKernelData("embed_test_library", CudaKernelFmt::Ptx));
 * if (!bin.data) {
 *     throw std::runtime_error("Kernel not embedded in this build");
 * }
 *
 * CUmodule module{};
 * ORTEAF_CUDA_DRIVER_CHECK(cuModuleLoadData(&module, bin.data));
 * CUfunction fn{};
 * ORTEAF_CUDA_DRIVER_CHECK(cuModuleGetFunction(&fn, module, "my_kernel"));
 * // ... enqueue kernel with cuLaunchKernel/cudaLaunchKernel ...
 * @endcode
 */

enum class CudaKernelFmt { Fatbin, Cubin, Ptx };

constexpr const char* toString(CudaKernelFmt fmt) noexcept {
    switch (fmt) {
    case CudaKernelFmt::Fatbin: return "fatbin";
    case CudaKernelFmt::Cubin: return "cubin";
    case CudaKernelFmt::Ptx: return "ptx";
    }
    return "unknown";
}

struct Blob {
    const void* data;
    std::size_t size;
};

Blob findKernelData(std::string_view name,
                      CudaKernelFmt prefer = CudaKernelFmt::Fatbin,
                      Blob fallback = {nullptr, 0});

bool available(std::string_view name, CudaKernelFmt fmt);

} // namespace orteaf::internal::execution::cuda::platform::wrapper::kernel_embed

#endif  // ORTEAF_ENABLE_CUDA
