#pragma once

#include "orteaf/internal/backend/mps/mps_device.h"
#include "orteaf/internal/backend/mps/mps_function.h"
#include "orteaf/internal/backend/mps/mps_error.h"
#include "orteaf/internal/backend/mps/mps_library.h"

#include <cstddef>
#include <string_view>

namespace orteaf::internal::backend::mps::metal_kernel_embed {

/**
 * @brief Access embedded Metal (MPS) metallib blobs generated by CMake.
 *
 * `.metal` sources placed under `orteaf/src/extension/kernel/mps/impl` are
 * compiled via `xcrun metal`/`metallib`, embedded into the binary, and exposed
 * through this registry.  These helpers allow backends to construct
 * `MTLLibrary` / `MTLFunction` objects without touching the filesystem, which
 * is convenient for tests and for distributing self-contained binaries.
 *
 * @par Usage example
 * @code{.mm}
 * using namespace orteaf::internal::backend::mps;
 * using namespace orteaf::internal::backend::mps::metal_kernel_embed;
 *
 * MPSDevice_t device = acquire_default_device();  // user-defined helper
 * MPSError_t error = nullptr;
 * MPSFunction_t fn = load_embedded_function(device,
 *                                           "embed_test_library",
 *                                           "my_kernel",
 *                                           &error);
 * if (fn == nil) {
 *     // 'error' carries an autoreleased NSError-style object.
 *     handle_mps_error(error);
 * }
 * // Continue with pipeline creation, command encoder setup, etc.
 * @endcode
 */

struct MetallibBlob {
    const void* data;
    std::size_t size;
};

MetallibBlob find_library_data(std::string_view library_name);

bool available(std::string_view library_name);

MPSFunction_t load_embedded_function(MPSDevice_t device,
                                     std::string_view library_name,
                                     std::string_view function_name,
                                     MPSError_t* error = nullptr);

} // namespace orteaf::internal::backend::mps::metal_kernel_embed
